In [3]:
# Load libraries
import pandas
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [178]:
file="/home/prashant/movilens_dataset/ml-100k/u.data"

In [179]:
names=['user_id','item_id','rating','timestamp']

In [180]:
movies_dataset =pandas.read_csv(file,delimiter="\t", names=names)

In [181]:
movies_dataset

       user_id  item_id  rating  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
5          298      474       4  884182806
6          115      265       2  881171488
7          253      465       5  891628467
8          305      451       3  886324817
9            6       86       3  883603013
10          62      257       2  879372434
11         286     1014       5  879781125
12         200      222       5  876042340
13         210       40       3  891035994
14         224       29       3  888104457
15         303      785       3  879485318
16         122      387       5  879270459
17         194      274       2  879539794
18         291     1042       4  874834944
19         234     1184       2  892079237
20         119      392       4  886176814
21         167      486       4  892738452
22         299      144       4  877881320
23         291      118       2  874833878
24         308        1       4  887736532
25          95      546       2  879196566
26          38       95       5  892430094
27         102      768       2  883748450
28          63      277       4  875747401
29         160      234       5  876861185
...        ...      ...     ...        ...
99970      449      120       1  879959573
99971      661      762       2  876037121
99972      721      874       3  877137447
99973      821      151       4  874792889
99974      764      596       3  876243046
99975      537      443       3  886031752
99976      618      628       2  891308019
99977      487      291       3  883445079
99978      113      975       5  875936424
99979      943      391       2  888640291
99980      864      685       4  888891900
99981      750      323       3  879445877
99982      279       64       1  875308510
99983      646      750       3  888528902
99984      654      370       2  887863914
99985      617      582       4  883789294
99986      913      690       3  880824288
99987      660      229       2  891406212
99988      421      498       4  892241344
99989      495     1091       4  888637503
99990      806      421       4  882388897
99991      676      538       4  892685437
99992      721      262       3  877137285
99993      913      209       2  881367150
99994      378       78       3  880056976
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

In [182]:
print(movies_dataset.shape)

(100000, 4)

In [183]:
print(movies_dataset.describe())

            user_id        item_id         rating     timestamp
count  100000.00000  100000.000000  100000.000000  1.000000e+05
mean      462.48475     425.530130       3.529860  8.835289e+08
std       266.61442     330.798356       1.125674  5.343856e+06
min         1.00000       1.000000       1.000000  8.747247e+08
25%       254.00000     175.000000       3.000000  8.794487e+08
50%       447.00000     322.000000       4.000000  8.828269e+08
75%       682.00000     631.000000       4.000000  8.882600e+08
max       943.00000    1682.000000       5.000000  8.932866e+08

In [184]:
# the functions on a dataframe gives a series
listing_series = movies_dataset.groupby('item_id',sort=True).size()

In [185]:
#converting series to a dataframe
listing_df = listing_series.to_frame()

In [186]:
type(listing_df)

pandas.core.frame.DataFrame

In [187]:
listing_df = listing_df.rename(columns={0:"count_times_rated"})

In [188]:
listing_df = listing_df.sort_values("count_times_rated", ascending=False)

In [189]:
listing_df = listing_df.reset_index()

In [190]:
listing_df

      item_id  count_times_rated
0          50                583
1         258                509
2         100                508
3         181                507
4         294                485
5         286                481
6         288                478
7           1                452
8         300                431
9         121                429
10        174                420
11        127                413
12         56                394
13          7                392
14         98                390
15        237                384
16        117                378
17        172                367
18        222                365
19        313                350
20        204                350
21        405                344
22         79                336
23        210                331
24        151                326
25        173                324
26         69                321
27        748                316
28        168                316
29        269                315
...       ...                ...
1652     1340                  1
1653     1339                  1
1654     1595                  1
1655     1596                  1
1656     1329                  1
1657     1599                  1
1658     1325                  1
1659     1601                  1
1660     1603                  1
1661     1604                  1
1662     1583                  1
1663     1581                  1
1664     1564                  1
1665     1580                  1
1666     1565                  1
1667     1566                  1
1668     1567                  1
1669     1568                  1
1670     1569                  1
1671     1570                  1
1672     1571                  1
1673     1572                  1
1674     1349                  1
1675     1574                  1
1676     1575                  1
1677     1576                  1
1678     1577                  1
1679     1348                  1
1680     1579                  1
1681     1682                  1

[1682 rows x 2 columns]

In [191]:
movies_file="/home/prashant/movilens_dataset/ml-100k/u.item"

In [192]:
names=['movie_id','movie_title','release_date','video_release_date','IMDb_URL','unknown','Action','Adventure','Animation','Children''s','Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western']

In [193]:
movies_list =pandas.read_csv(movies_file,delimiter="|", names=names , encoding='latin-1')

In [194]:
movies_list

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Childrens,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
5,6,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,01-Jan-1995,NaN,http://us.imdb.com/Title?Yao+a+yao+yao+dao+wai...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,Twelve Monkeys (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Twelve%20Monk...,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7,8,Babe (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Babe%20(1995),0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8,9,Dead Man Walking (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Dead%20Man%20...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10,Richard III (1995),22-Jan-1996,NaN,http://us.imdb.com/M/title-exact?Richard%20III...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10,11,Seven (Se7en) (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Se7en%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
11,12,"Usual Suspects, The (1995)",14-Aug-1995,NaN,http://us.imdb.com/M/title-exact?Usual%20Suspe...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12,13,Mighty Aphrodite (1995),30-Oct-1995,NaN,http://us.imdb.com/M/title-exact?Mighty%20Aphr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,14,"Postino, Il (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?Postino,%20Il...",0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
14,15,Mr. Holland's Opus (1995),29-Jan-1996,NaN,http://us.imdb.com/M/title-exact?Mr.%20Holland...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,16,French Twist (Gazon maudit) (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Gazon%20maudi...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
16,17,From Dusk Till Dawn (1996),05-Feb-1996,NaN,http://us.imdb.com/M/title-exact?From%20Dusk%2...,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
17,18,"White Balloon, The (1995)",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Badkonake%20S...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,19,Antonia's Line (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Antonia%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,20,Angels and Insects (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Angels%20and%...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
20,21,Muppet Treasure Island (1996),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Muppet%20Trea...,0,1,1,0,0,...,0,0,0,1,0,0,0,1,0,0
21,22,Braveheart (1995),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Braveheart%20...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22,23,Taxi Driver (1976),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Taxi%20Driver...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,24,Rumble in the Bronx (1995),23-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Hong%20Faan%2...,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
24,25,"Birdcage, The (1996)",08-Mar-1996,NaN,"http://us.imdb.com/M/title-exact?Birdcage,%20T...",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,26,"Brothers McMullen, The (1995)",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Brothers%20Mc...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,27,Bad Boys (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Bad%20Boys%20...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,28,Apollo 13 (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Apollo%2013%2...,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
28,29,Batman Forever (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Batman%20Fore...,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
29,30,Belle de jour (1967),01-Jan-1967,NaN,http://us.imdb.com/M/title-exact?Belle%20de%20...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1652,1653,Entertaining Angels: The Dorothy Day Story (1996),27-Sep-1996,NaN,http://us.imdb.com/M/title-exact?Entertaining%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1653,1654,Chairman of the Board (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Chairman+of+the+Board...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1654,1655,"Favor, The (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?Favor,%20The%...",0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1655,1656,Little City (1998),20-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Little+City+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1656,1657,Target (1995),28-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Target%20(1995),0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1657,1658,"Substance of Fire, The (1996)",06-Dec-1996,NaN,http://us.imdb.com/M/title-exact?Substance%20o...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1658,1659,Getting Away With Murder (1996),12-Apr-1996,NaN,http://us.imdb.com/Title?Getting+Away+With+Mur...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1659,1660,Small Faces (1995),09-Aug-1996,NaN,http://us.imdb.com/M/title-exact?Small%20Faces...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1660,1661,"New Age, The (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?New%20Age,%20...",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1661,1662,Rough Magic (1995),30-May-1997,NaN,http://us.imdb.com/M/title-exact?Rough%20Magic...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1662,1663,Nothing Personal (1995),30-Apr-1997,NaN,http://us.imdb.com/M/title-exact?Nothing%20Per...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1663,1664,8 Heads in a Duffel Bag (1997),18-Apr-1997,NaN,http://us.imdb.com/Title?8+Heads+in+a+Duffel+B...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1664,1665,"Brother's Kiss, A (1997)",25-Apr-1997,NaN,http://us.imdb.com/M/title-exact?Brother%27s%2...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1665,1666,Ripe (1996),02-May-1997,NaN,http://us.imdb.com/M/title-exact?Ripe%20%28199...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1666,1667,"Next Step, The (1995)",13-Jun-1997,NaN,http://us.imdb.com/M/title-exact?Next%20Step%2...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1667,1668,Wedding Bell Blues (1996),13-Jun-1997,NaN,http://us.imdb.com/M/title-exact?Wedding%20Bel...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1668,1669,MURDER and murder (1996),20-Jun-1997,NaN,http://us.imdb.com/M/title-exact?MURDER+and+mu...,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1669,1670,Tainted (1998),01-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Tainted+(1998),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1670,1671,"Further Gesture, A (1996)",20-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Further+Gestu...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1671,1672,Kika (1993),01-Jan-1993,NaN,http://us.imdb.com/M/title-exact?Kika%20(1993),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1672,1673,Mirage (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Mirage%20(1995),0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1673,1674,Mamma Roma (1962),01-Jan-1962,NaN,http://us.imdb.com/M/title-exact?Mamma%20Roma%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1674,1675,"Sunchaser, The (1996)",25-Oct-1996,NaN,"http://us.imdb.com/M/title-exact?Sunchaser,%20...",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1675,1676,"War at Home, The (1996)",01-Jan-1996,NaN,http://us.imdb.com/M/title-exact?War%20at%20Ho...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1676,1677,Sweet Nothing (1995),20-Sep-1996,NaN,http://us.imdb.com/M/title-exact?Sweet%20Nothi...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [195]:
final_movies_df = pandas.merge(listing_df, movies_list, how='inner', left_on = 'item_id', right_on = 'movie_id')

In [196]:
final_movies_df = final_movies_df.drop(['item_id','video_release_date','IMDb_URL','unknown','Action','Adventure','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western','Animation','Childrens','Comedy','Crime','Documentary','Drama'],axis=1)

In [197]:
final_movies_df

,count_times_rated,movie_id,movie_title,release_date
0,583,50,Star Wars (1977),01-Jan-1977
1,509,258,Contact (1997),11-Jul-1997
2,508,100,Fargo (1996),14-Feb-1997
3,507,181,Return of the Jedi (1983),14-Mar-1997
4,485,294,Liar Liar (1997),21-Mar-1997
5,481,286,"English Patient, The (1996)",15-Nov-1996
6,478,288,Scream (1996),20-Dec-1996
7,452,1,Toy Story (1995),01-Jan-1995
8,431,300,Air Force One (1997),01-Jan-1997
9,429,121,Independence Day (ID4) (1996),03-Jul-1996
10,420,174,Raiders of the Lost Ark (1981),01-Jan-1981
11,413,127,"Godfather, The (1972)",01-Jan-1972
12,394,56,Pulp Fiction (1994),01-Jan-1994
13,392,7,Twelve Monkeys (1995),01-Jan-1995
14,390,98,"Silence of the Lambs, The (1991)",01-Jan-1991
15,384,237,Jerry Maguire (1996),13-Dec-1996
16,378,117,"Rock, The (1996)",07-Jun-1996
17,367,172,"Empire Strikes Back, The (1980)",01-Jan-1980
18,365,222,Star Trek: First Contact (1996),22-Nov-1996
19,350,313,Titanic (1997),01-Jan-1997
20,350,204,Back to the Future (1985),01-Jan-1985
21,344,405,Mission: Impossible (1996),22-May-1996
22,336,79,"Fugitive, The (1993)",01-Jan-1993
23,331,210,Indiana Jones and the Last Crusade (1989),01-Jan-1989
24,326,151,Willy Wonka and the Chocolate Factory (1971),01-Jan-1971
25,324,173,"Princess Bride, The (1987)",01-Jan-1987
26,321,69,Forrest Gump (1994),01-Jan-1994
27,316,748,"Saint, The (1997)",14-Mar-1997
28,316,168,Monty Python and the Holy Grail (1974),01-Jan-1974
29,315,269,"Full Monty, The (1997)",01-Jan-1997
...,...,...,...,...
1652,1,1340,"Crude Oasis, The (1995)",01-Jan-1995
1653,1,1339,Stefano Quantestorie (1993),01-Jan-1993
1654,1,1595,Shopping (1994),09-Feb-1996
1655,1,1596,Nemesis 2: Nebula (1995),01-Jan-1995
1656,1,1329,"Low Life, The (1994)",10-May-1996
1657,1,1599,Someone Else's America (1995),10-May-1996
1658,1,1325,August (1996),12-Apr-1996
1659,1,1601,Office Killer (1997),01-Jan-1997
1660,1,1603,Angela (1995),16-Feb-1996
1661,1,1604,He Walked by Night (1948),01-Jan-1948
1662,1,1583,"Invitation, The (Zaproszenie) (1986)",01-Jan-1986
1663,1,1581,"Woman in Question, The (1950)",01-Jan-1950
1664,1,1564,To Cross the Rubicon (1991),01-Jan-1991
1665,1,1580,Liebelei (1933),01-Jan-1933
1666,1,1565,Daens (1992),01-Jan-1992
1667,1,1566,"Man from Down Under, The (1943)",01-Jan-1943
1668,1,1567,Careful (1992),01-Jan-1992
1669,1,1568,Vermont Is For Lovers (1992),01-Jan-1992
1670,1,1569,"Vie est belle, La (Life is Rosey) (1987)",01-Jan-1987
1671,1,1570,Quartier Mozart (1992),01-Jan-1992
1672,1,1571,Touki Bouki (Journey of the Hyena) (1973),01-Jan-1973
1673,1,1572,Wend Kuuni (God's Gift) (1982),01-Jan-1982
1674,1,1349,Mille bolle blu (1993),01-Jan-1993
1675,1,1574,Pharaoh's Army (1995),01-Jan-1995
1676,1,1575,"I, Worst of All (Yo, la peor de todas) (1990)",01-Jan-1990
1677,1,1576,"Hungarian Fairy Tale, A (1987)",01-Jan-1987
1678,1,1577,"Death in the Garden (Mort en ce jardin, La) (1...",01-Jan-1956
1679,1,1348,Every Other Weekend (1990),01-Jan-1990
1680,1,1579,Baton Rouge (1988),01-Jan-1988
1681,1,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996